spring.application.name=admissio-scrapper
server.port=8081

spring.profiles.active=local

spring.datasource.username=admissio
spring.datasource.password=password

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

scraper.osvita.api.token=0.ZwSDQYf5O8J0VAmqXXrp-QTwy5NjO9rpM2uLYEP52iohG5fGV-3n3oCT2T6XmmWWTfVYHyqybuk7b1_rD10weXzLYM-vWUyOBOZCBysOe7WFUMzc_SDHSYQlKYOa_EDJaDQl8o51NREigwXuc7dsUvSgyeSACDNQDDuny9ExNAEqUSJtg4k3oPqSXFgJvl4Sp5cKD7vMHuDzARDXqXfQEJRDBGXoccIZUboWPFBvjuWFJbEnJy1cOH7utO53DLdsOPpXUxipmPv6WdYN5UT3Ev4SdxL3Avp0BP-1mVUHSC1NWDcl0JkkOM0qWPtQSqnrGjTNJ0kf8rmAxAeY7D0HdA-D4Ymvcecrhl2JtX1B7ijja_2f2iPMx3fScquYxuOGP3hVvBAleAUd9terWfhctkK_zc2gnmQmwzz_pQVY-156wpsFsGYP1Be396KU_eEutt3dfi6mw8ERr6uQxexKZbr1jpWf9kEGHaqgwN4FDTN8SMGib3V--1wm1rIrxXs02fCrNgQqLq6dsEGAHUoGQgFYGhA8tu_Ydtq4O7ZZZO3x9yogeOEtCKzXrRGVUOLpmhAl-19oqvo46isXvDPBY-oxufAB20J7yIlq3xH8MmPqWJogO7kgWkTnFMSUmH5lETI8SkLPln_jIJjJ74MJ__xYuwUGS9H_Frlk1R5JqptwITJOZ0zbkFQnPwCOceKg0-XQJkN6cStEOjyZj6sbVDHlbV0z3O7Rfmh8Vqk4KnZIOEx00aynPcoDvzmn3i8HDpq1dqTO4kOzUrn6I4NCe2z36M1HMFfUMifvtcklaZ64NYD7LWUmoAp9BNqq2ewBl_RW2q0i6OSkEOaR1ZZfUW5FHf78T9x6suk26m0_FUQoRD5cgwrY3Rfrfs7R_b0AX4O2V9a7tO_KJgt81-rbQmdjOp5hXDdem5UJGGfNPiNuCXoOrH-yQFWlhxlmsAuWXlVwx4o8kwN2A1rl3SvgsQ.n4_iy-idBiThT3XRcZ9QyQ.f68c1290ca017599153d711c296ccc33d3802367af891d705a76c269bedad18c
scraper.osvita.api.cookie=_ga=GA1.1.1546464469.1727005325; cf_clearance=XlCUCOTerxmWbd3fo.5hxmHkDifZzW3NjgbgGUnJQ.Q-1736707807-1.2.1.1-hS6EUh.hSV6s.TDAXOq8UiBQJQFgDKT.8IqMqse1smdXR3jh19h8y_PEpqvpFMckXuAUqFXkGmsgJPvOZjLyUjercK9ok8Upep_5FGHiFMTBYcCNrLFIwTc6rQ_IrkXJOxp0oyCAue0kTgn.gFVwq.mXVMPmKEvRn6EU614I9fgmS9ZYrocnMMh9qAf_sDw2oO7.lTX93AB_Nn8HtqQ3xOrhrxGIKnwor31KRlhI3CokeyDfOVISqgp3eIUtcQKEq8SkxeU9RKciuLl2pvPLkJYLoONyFxP11QyAiKOOkFk; PHPSESSID=ae5a5dba67ba75fea095c434817bef73; fvbr=Chrome; _ga_249WW3GG5N=GS2.1.s1754334673$o22$g1$t1754334676$j57$l0$h0; _ga_WM6Y0LDHD6=GS2.1.s1754389258$o26$g1$t1754391004$j48$l0$h0; _ga_F00FRGG1W3=GS2.1.s1754389258$o40$g1$t1754391004$j48$l0$h0; sdv=1754391011

scraper.edbo.api.cookie=PHPSESSID=u4udo6v94qts74e0824ecf7tds; _ga=GA1.1.82258330.1752844035; _ga_YC32TV7WL7=GS2.1.s1753629418$o3$g0$t1753629423$j55$l0$h0; _ga_W6WT1K3VXZ=GS2.1.s1753801727$o1$g0$t1753801727$j60$l0$h0; _ga_96Q7K30V0N=GS2.1.s1754472938$o60$g1$t1754473509$j47$l0$h0